# Generated by Django 4.2.5 on 2023-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('name', models.CharField(error_messages='Максимум 50 символов', max_length=50, null=True, verbose_name='Имя заказчика')),
                ('phone', models.CharField(error_messages='Максимум 15 символов', max_length=15, null=True, verbose_name='Телефон заказчика')),
                ('mail', models.EmailField(blank=True, error_messages='Не правильный формат e-mail', max_length=50, null=True, verbose_name='Эл.почта заказчика')),
                ('message', models.TextField(error_messages='Максимум 1000 символов', max_length=1000, null=True, verbose_name='Сообщение')),
                ('files', models.FileField(blank=True, error_messages='Неправильный формат файла', max_length=1000, null=True, upload_to='media/%Y/%m/%d', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
