# Generated by Django 4.2.5 on 2023-10-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.CharField(choices=[('offer', 'Главное Предложение'), ('info', 'О нас'), ('advantage', 'Преимущество нашей продукции'), ('works', 'Наши работы'), ('made', 'Этапы производства'), ('partnership', 'Сотрудничество'), ('accordeon', 'Вопросы')], null=True, verbose_name='Категория')),
                ('version', models.CharField(max_length=3, null=True, verbose_name='Версия')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Имя')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('url', models.URLField(blank=True, default='https://', verbose_name='Ссылка URL:')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Версия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('accordeon', models.ManyToManyField(limit_choices_to={'category': 'accordeon'}, related_name='accordeon', to='home.card', verbose_name='Частые вопросы')),
                ('advantage', models.ManyToManyField(limit_choices_to={'category': 'advantage'}, related_name='advantage', to='home.card', verbose_name='Из чего наша продукция')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Форма обратной связи')),
                ('info', models.ManyToManyField(limit_choices_to={'category': 'info'}, related_name='info', to='home.card', verbose_name='О нас')),
                ('made', models.ManyToManyField(limit_choices_to={'category': 'made'}, related_name='made', to='home.card', verbose_name='Этапы выполнения заказа')),
                ('offer', models.ManyToManyField(limit_choices_to={'category': 'offer'}, related_name='offer', to='home.card', verbose_name='Главное предложение')),
                ('partnership', models.ManyToManyField(limit_choices_to={'category': 'partnership'}, related_name='partnership', to='home.card', verbose_name='Как происходит сотрудничество')),
                ('works', models.ManyToManyField(limit_choices_to={'category': 'works'}, related_name='works', to='home.card', verbose_name='Наши работы')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
                'ordering': ['-created_at'],
            },
        ),
    ]
