# Generated by Django 4.2.5 on 2023-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('name', models.CharField(null=True, unique=True, verbose_name='Имя')),
                ('adress', models.CharField(max_length=50, null=True, unique=True, verbose_name='Адрес заказчика')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Телефон заказчика')),
                ('mail', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Эл.почта заказчика')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
