services:

  database:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"

  mebel:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./mebel:/mebel
    restart: always
    command: >
      sh -c "python manage.py runserver"
    depends_on:
      - database
