version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: shukik/mebel:latest
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    command: gunicorn mebel.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
