# Generated by Django 4.2.5 on 2023-10-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='theme',
            field=models.CharField(default='New', verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
