# Generated by Django 4.2.5 on 2023-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Имя')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('url', models.URLField(blank=True, default='https://', verbose_name='Ссылка URL:')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['name'],
            },
        ),
    ]
